import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="grid grid-cols-12 gap-4 bg-slate-100 h-screen">
          <div className="col-span-2 bg-blue-800 h-full">
            <Sidebar />
          </div>
          <div className="col-span-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
